apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app # Define the Deployment Name
spec:
  selector: # Define the Selector
    matchLabels:
      run: python-flask-app
  replicas: 2 # Define the Number of Pods
  template:
    metadata:
      labels:
        run: python-flask-app
    spec:
      containers: # Container Details
      - name: python-flask-app
        image: tobiasreaper/python-flask-app:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: python-flask-app
  labels:
    run: python-flask-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    run: python-flask-app
